### ISSUE TITLE
Does not work with current Doctrine version for Neos ^7.3/^8.0

### ISSUE THREAD

**Issue by mrk131324** [punktDe/noderestrictions#8]
Class `ParentNodePropertyGenerator` requires `Doctrine\Common\Persistence\Mapping\ClassMetadata` which is not available anymore in Neos 8. Either use `Neos\Flow\Persistence\Doctrine\Mapping\ClassMetadata` or `\Doctrine\ORM\Mapping\ClassMetadata`.

**Comment by crydotsnake** [comment]
Can confirm this is also reproducable with Neos 7.3

**Comment by crydotsnake** [comment]
Fixed in https://github.com/punktDe/noderestrictions/releases/tag/2.0.4
